version: '3.9'

services:
  bot:
    container_name: "videoroundbot_dev"
    build:
      context: .
    network_mode: host
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
